services:
    db:
        image: postgres
        ports:
            - ${DB_PORT}
        environment:
            - POSTGRES_PASSWORD=${DB_ROOT_PASSWORD}
            - PGUSER=${DB_USER}
            - PGPASSWORD=${DB_PASSWORD}
            - PGDATABASE=${DB_NAME}
            - PGPORT=${DB_PORT}
        volumes:
            - local-data:/var/lib/postgresql/data

    www:
        build: ./
        ports:
            - "${PORT}:3000"
        depends_on:
            - db
        volumes:
            - ./:/app/src
        environment:
            - DB_HOST=db
            - DB_PORT=${DB_PORT}

volumes:
  local-data:
