#!/usr/bin/env bash
set -e

main()
{
    case $1 in
        shell)
            bash
            ;;
        dev)
            printf "\t ..: Starting developer mode\n"
            NODE_ENV=development yarn dev
            ;;
        *)
            printf "\t ..: Invoking yarn with '$*'\n"
            yarn "$*"
            ;;
    esac
}

# next needs the public folder to be mapped in its project root
ln -s ./src/public ./public

main "$@"
