#!/usr/bin/env bash
set -e

main()
{
    case $1 in
        shell)
            bash
            ;;
        dev)
            printf "\t ..: Starting developer mode\n"
            export NODE_ENV=development
            yarn dev
            ;;
        *)
            printf "\t ..: Invoking yarn with '$*'\n"
            yarn "$*"
            ;;
    esac
}

main "$@"
