#!/usr/bin/env bash

set -e

main()
{
    case $1 in
        "")
            printf "\t ..: Starting in production mode\n"
            export NODE_ENV=production
            yarn start
            ;;
        shell)
            bash
            ;;
        develop)
            printf "\t ..: Starting developer mode\n"
            export NODE_ENV=production
            yarn run test:all
            ;;
    esac
}

# cd /app/src
main "$@"
